# Read the Docs configuration file for TypeDoc
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "22"
  commands:
    - npm ci
    - npm run docs
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs-dist/* $READTHEDOCS_OUTPUT/html/
